import { readFileSync, writeFileSync } from 'fs';
let c = readFileSync('src/App.js', 'utf8');
c = c.replace(/\r\n/g, '\n');

const caStart = `lastUpdated: 'Spring 2024 Reports to Parliament',\n            findings: [`;
const caEnd   = `\n            ],\n          },\n          results: [`;

const startIdx = c.indexOf(caStart);
if (startIdx === -1) { console.log('ERROR: CA start not found'); process.exit(1); }
const endIdx = c.indexOf(caEnd, startIdx);
if (endIdx === -1) { console.log('ERROR: CA end not found'); process.exit(1); }

const caNew = `lastUpdated: 'Spring 2024 Reports to Parliament',
            findings: [
              { id: 'arrivecan',          title: 'ArriveCAN App — $60M for an $80,000 Application',          auditBody: 'Office of the Auditor General (OAG)',            date: 'February 2023', severity: 'critical', amountAtRisk: '$59.5M overspent',            description: 'The OAG found the ArriveCAN app cost $59.5M — far exceeding its $80,000 estimated value — due to undocumented contracts, missing receipts, and payments to GCstrategies with no supporting records.',           authorized: '$59.5M CAD',                         breakdown: [{ label: 'Direct to Purpose',            color: '#22c55e', pct: 8,  amount: '$4.76M',  note: 'Verified software development delivered to CBSA specifications' }, { label: 'Administration & Overhead',   color: '#8b5cf6', pct: 12, amount: '$7.14M',  note: 'CBSA internal project oversight, management and coordination costs' }, { label: 'Contractors & Consultants',   color: '#f97316', pct: 62, amount: '$36.9M',  note: 'GCstrategies and subcontractors; many invoices lacked supporting documentation' }, { label: 'NGOs & Intermediary Networks', color: '#06b6d4', pct: 0,  amount: '$0',      note: 'No nonprofit or third-party intermediary funding identified in this program' }, { label: 'Unknown or Undisclosed',      color: '#ef4444', pct: 18, amount: '$10.7M',  note: 'Payments with no receipts, undocumented deliverables or missing contract records' }, { label: 'Recovered or Clawed Back',    color: '#84cc16', pct: 0,  amount: '$0',      note: 'No funds recovered from contractors as of the OAG reporting date' }] },
              { id: 'phoenix-pay',        title: 'Phoenix Pay System — Ongoing Remediation Failure',        auditBody: 'Office of the Auditor General (OAG)',            date: 'May 2024',      severity: 'critical', amountAtRisk: '$3.5B+ in remediation costs',         description: 'Despite $3.5B in remediation spending since 2016, the OAG found the federal pay system continues to produce incorrect payments for thousands of employees, with the replacement NextGen HR system years behind its scheduled delivery.', authorized: '$3.5B+ CAD',                         breakdown: [{ label: 'Direct to Purpose',            color: '#22c55e', pct: 31, amount: '$1.09B',  note: 'Original IBM and Ceridian implementation costs for the Phoenix system build' }, { label: 'Administration & Overhead',   color: '#8b5cf6', pct: 18, amount: '$630M',   note: 'PSPC internal project governance, testing teams and departmental pay staff' }, { label: 'Contractors & Consultants',   color: '#f97316', pct: 38, amount: '$1.33B',  note: 'IT remediation consultants and NextGen HR replacement system development' }, { label: 'NGOs & Intermediary Networks', color: '#06b6d4', pct: 0,  amount: '$0',      note: 'No third-party nonprofit involvement in the Phoenix remediation program' }, { label: 'Unknown or Undisclosed',      color: '#ef4444', pct: 13, amount: '$455M',   note: 'Remediation spending without clear outcome attribution or documented results' }, { label: 'Recovered or Clawed Back',    color: '#84cc16', pct: 0,  amount: '$0',      note: 'No cost recovery from vendors despite years of systemic underperformance' }] },
              { id: 'cerb-overpay',       title: 'COVID-19 CERB and Emergency Benefit Overpayments',       auditBody: 'Office of the Auditor General (OAG)',            date: 'May 2023',      severity: 'high',     amountAtRisk: '$4.6B overpaid',                      description: 'The OAG found $4.6B in CERB and pandemic emergency benefit payments made to ineligible recipients, including incarcerated individuals and minors. Less than 15% has been recovered by CRA to date.',                  authorized: '$4.6B CAD (improper payments)',       breakdown: [{ label: 'Direct to Purpose',            color: '#22c55e', pct: 48, amount: '$2.21B',  note: 'Paid to individuals with income loss later found to be borderline eligible' }, { label: 'Administration & Overhead',   color: '#8b5cf6', pct: 11, amount: '$506M',   note: 'CRA processing systems, verification operations and recovery program costs' }, { label: 'Contractors & Consultants',   color: '#f97316', pct: 6,  amount: '$276M',   note: 'Technical contractors supporting CRA digital delivery and call center operations' }, { label: 'NGOs & Intermediary Networks', color: '#06b6d4', pct: 0,  amount: '$0',      note: 'CERB was paid directly to individuals; no NGO intermediaries were used' }, { label: 'Unknown or Undisclosed',      color: '#ef4444', pct: 24, amount: '$1.10B',  note: 'Payments to individuals where eligibility could not be retroactively verified' }, { label: 'Recovered or Clawed Back',    color: '#84cc16', pct: 11, amount: '$506M',   note: 'CRA recovery through reassessments and voluntary repayment plans to date' }] },
              { id: 'indigenous-housing', title: 'Indigenous On-Reserve Housing — No National Strategy',   auditBody: 'Office of the Auditor General (OAG)',            date: 'March 2024',    severity: 'high',     amountAtRisk: '$4.3B spent, gap unresolved',          description: 'The OAG found that despite $4.3B in federal housing investment, Indigenous Services Canada has no reliable data on the reserve housing deficit and no national strategy to close it. Conditions have not measurably improved.',   authorized: '$4.3B CAD',                          breakdown: [{ label: 'Direct to Purpose',            color: '#22c55e', pct: 41, amount: '$1.76B',  note: 'On-reserve housing construction, materials, labor and community development' }, { label: 'Administration & Overhead',   color: '#8b5cf6', pct: 22, amount: '$946M',   note: 'ISC departmental overhead, regional offices and program coordination costs' }, { label: 'Contractors & Consultants',   color: '#f97316', pct: 19, amount: '$817M',   note: 'External project managers, engineering firms and housing consultants' }, { label: 'NGOs & Intermediary Networks', color: '#06b6d4', pct: 11, amount: '$473M',   note: 'Regional Indigenous organizations and housing associations receiving federal grants' }, { label: 'Unknown or Undisclosed',      color: '#ef4444', pct: 7,  amount: '$301M',   note: 'Spending without documented housing unit outcomes or beneficiary records' }, { label: 'Recovered or Clawed Back',    color: '#84cc16', pct: 0,  amount: '$0',      note: 'No clawbacks applied despite OAG finding of unverifiable outcomes' }] },
              { id: 'mckinsey-contracts', title: 'McKinsey & Company Federal Contracts — Sole-Source Awards', auditBody: 'Public Services and Procurement Canada / OAG', date: 'October 2023',  severity: 'high',     amountAtRisk: '$209M in contracts awarded',           description: 'An audit found $209M in federal contracts awarded to McKinsey & Company, many without competitive bidding, with inadequate documentation of deliverables and value received by taxpayers.',                                         authorized: '$209M CAD',                          breakdown: [{ label: 'Direct to Purpose',            color: '#22c55e', pct: 29, amount: '$60.6M',  note: 'Consulting work with documented reports and verified recommendations to government' }, { label: 'Administration & Overhead',   color: '#8b5cf6', pct: 9,  amount: '$18.8M',  note: 'Federal procurement officers, contract management and internal legal review costs' }, { label: 'Contractors & Consultants',   color: '#f97316', pct: 58, amount: '$121.2M', note: 'McKinsey fees across departments; majority of contracts awarded without competitive bids' }, { label: 'NGOs & Intermediary Networks', color: '#06b6d4', pct: 0,  amount: '$0',      note: 'No nonprofit involvement; contracts were direct government-to-McKinsey awards' }, { label: 'Unknown or Undisclosed',      color: '#ef4444', pct: 4,  amount: '$8.4M',   note: 'Contracts where deliverables were not documented or made publicly available' }, { label: 'Recovered or Clawed Back',    color: '#84cc16', pct: 0,  amount: '$0',      note: 'No funds recovered; contracting practices reviewed but no clawback was pursued' }] },
              { id: 'dental-plan',        title: 'Canada Dental Care Plan — Rollout Delays and Gaps',       auditBody: 'Office of the Auditor General (OAG)',            date: 'November 2024', severity: 'medium',   amountAtRisk: '$4.4B allocated',                      description: 'The OAG found enrollment delays, unclear eligibility rules, and no outcome tracking in the first year of the dental plan rollout. Only 48% of the $4.4B allocated budget was disbursed to enrollees.',                         authorized: '$4.4B CAD',                          breakdown: [{ label: 'Direct to Purpose',            color: '#22c55e', pct: 48, amount: '$2.11B',  note: 'Benefit claims paid to enrolled Canadians for dental services received' }, { label: 'Administration & Overhead',   color: '#8b5cf6', pct: 15, amount: '$660M',   note: 'Health Canada oversight, eligibility systems and enrollment platform costs' }, { label: 'Contractors & Consultants',   color: '#f97316', pct: 22, amount: '$968M',   note: 'Sun Life Financial administration fees under the plan delivery contract' }, { label: 'NGOs & Intermediary Networks', color: '#06b6d4', pct: 0,  amount: '$0',      note: 'No NGO intermediaries; plan administered directly through Sun Life Financial' }, { label: 'Unknown or Undisclosed',      color: '#ef4444', pct: 15, amount: '$660M',   note: 'Unspent allocation from year one due to enrollment delays and rollout gaps' }, { label: 'Recovered or Clawed Back',    color: '#84cc16', pct: 0,  amount: '$0',      note: 'No recovery required; unspent year-one funds remain in the program allocation' }] },
              { id: 'shipbuilding',       title: 'National Shipbuilding Strategy — Delays and Cost Overruns', auditBody: 'Office of the Auditor General (OAG)',           date: 'April 2024',    severity: 'medium',   amountAtRisk: '$84B shipbuilding program',             description: 'The OAG found major schedule delays and cost growth across the National Shipbuilding Strategy, with combat and non-combat vessel projects years behind delivery dates and no credible revised timeline provided to Parliament.', authorized: '$84B CAD (full program)',              breakdown: [{ label: 'Direct to Purpose',            color: '#22c55e', pct: 45, amount: '$37.8B',  note: 'Vessel construction, steel, engineering and delivery on completed contract phases' }, { label: 'Administration & Overhead',   color: '#8b5cf6', pct: 16, amount: '$13.4B',  note: 'National Defence, PSPC and Coast Guard program management and oversight costs' }, { label: 'Contractors & Consultants',   color: '#f97316', pct: 29, amount: '$24.4B',  note: 'Irving Shipbuilding, Seaspan, subcontractors and naval design consultants' }, { label: 'NGOs & Intermediary Networks', color: '#06b6d4', pct: 0,  amount: '$0',      note: 'No NGO intermediary funding in defence and Coast Guard vessel procurement' }, { label: 'Unknown or Undisclosed',      color: '#ef4444', pct: 10, amount: '$8.4B',   note: 'Cost overruns and schedule slippages without clear accountability or documentation' }, { label: 'Recovered or Clawed Back',    color: '#84cc16', pct: 0,  amount: '$0',      note: 'No penalties applied to shipyards despite years of missed delivery milestones' }] },
              { id: 'green-procurement',  title: 'Federal Green Procurement — Widespread Missed Targets',   auditBody: 'Office of the Auditor General (OAG)',            date: 'October 2023',  severity: 'low',      amountAtRisk: '$22B annual procurement',               description: 'The OAG found 15 of 24 federal departments failed to meet green procurement targets, with inadequate training and no standard reporting framework across government, despite $22B in annual federal purchasing power.',        authorized: '$22B CAD (annual federal procurement)', breakdown: [{ label: 'Direct to Purpose',            color: '#22c55e', pct: 52, amount: '$11.4B',  note: 'Procurement contracts meeting environmental standards and verified green criteria' }, { label: 'Administration & Overhead',   color: '#8b5cf6', pct: 18, amount: '$4.0B',   note: 'Departmental procurement officers, Treasury Board oversight and compliance teams' }, { label: 'Contractors & Consultants',   color: '#f97316', pct: 21, amount: '$4.6B',   note: 'Vendors across departments where green compliance status was not assessed' }, { label: 'NGOs & Intermediary Networks', color: '#06b6d4', pct: 3,  amount: '$660M',   note: 'Community and environmental organizations receiving federal procurement subcontracts' }, { label: 'Unknown or Undisclosed',      color: '#ef4444', pct: 6,  amount: '$1.3B',   note: 'Contracts where green compliance was not assessed or documented by departments' }, { label: 'Recovered or Clawed Back',    color: '#84cc16', pct: 0,  amount: '$0',      note: 'No penalties applied to departments that failed to meet green procurement targets' }] },
            ]`;

c = c.slice(0, startIdx) + caNew + c.slice(endIdx);
console.log('CA breakdown data added OK');

writeFileSync('src/App.js', c, 'utf8');
console.log('Done. File size:', c.length);
